#ifndef ERRORS_H
#define ERRORS_H

#define ERR_OBJECT_NOT_FOUND 31603
#define ERR_INSUFFICIENT_PRIVILEGES 1031
#define ERR_TABLE_OR_VIEW_DOES_NOT_EXIST 942
#define ERR_COMPONENT_MUST_BE_DECALRED 302
#define ERR_IDENTIFIER_MUST_BE_DECLARED 201
#define ERR_INVALID_IDENTIFIER 904
#define ERR_PLS_ERROR_POSITION 6550
#define ERR_AMBIGUOUS_COLUMN_NAME 918
#define ERR_NAME_ALREADY_USED 918
#define ERR_CANNOT_SELECT_ROWID1 1445
#define ERR_CANNOT_SELECT_ROWID2 1446
#define ERR_OBJECT_DOES_NOT_EXIST 6564

#endif // ERRORS_H
