#ifndef ERRORS_H
#define ERRORS_H

#define ERR_OBJECT_NOT_FOUND 31603
#define ERR_INSUFFICIENT_PRIVILEGES 1031
#define ERR_TABLE_OR_VIEW_DOES_NOT_EXIST 942
#define ERR_COMPONENT_MUST_BE_DECALRED 302
#define ERR_INVALID_IDENTIFIER 904
#define ERR_PLS_ERROR_POSITION 6550
#define ERR_AMBIGUOUS_COLUMN_NAME 918
#define ERR_NAME_ALREADY_USED 918

#endif // ERRORS_H
