{@keep_if:>=10}
   select INST_ID, SID, SERIAL#, USERNAME, STATUS, COMMAND, SERVER,
   SCHEMANAME, OSUSER, PROCESS, MACHINE, TERMINAL,
   PROGRAM, TYPE, MODULE, ACTION, CLIENT_INFO, 
   LOGON_TIME from gv$session
{}
{@keep_if:<10}
   select SID, SERIAL#, USERNAME, STATUS, COMMAND, SERVER,
   SCHEMANAME, OSUSER, PROCESS, MACHINE, TERMINAL,
   PROGRAM, TYPE, MODULE, ACTION, CLIENT_INFO, 
   LOGON_TIME from v$session
{}
